import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const sources = [
  ["reference", "tokens/reference.tokens.json"],
  ["semantic", "tokens/semantic.tokens.json"],
  ["component", "tokens/component.tokens.json"],
];
const outputPath = resolve(root, "app/styles/generated/tokens.css");
const checkOnly = process.argv.includes("--check");

const kebab = (value) =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();

function toCssValue(value) {
  if (typeof value === "string") {
    const alias = value.match(/^\{(.+)}$/);
    return alias ? `var(--aa-${alias[1].split(".").map(kebab).join("-")})` : value;
  }
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map((item) => `"${item}"`).join(", ");
  if (value && typeof value === "object") {
    if (value.colorSpace === "srgb") {
      const [r, g, b] = value.components.map((component) => Math.round(component * 255));
      return value.alpha === 1 ? `rgb(${r} ${g} ${b})` : `rgb(${r} ${g} ${b} / ${value.alpha})`;
    }
    if ("value" in value && "unit" in value) return `${value.value}${value.unit}`;
  }
  throw new Error(`Unsupported token value: ${JSON.stringify(value)}`);
}

function collectTokens(node, path = [], inheritedType, output = []) {
  const type = node?.$type ?? inheritedType;
  if (node && typeof node === "object" && "$value" in node) {
    output.push({ path, type, value: toCssValue(node.$value) });
    return output;
  }
  for (const [key, value] of Object.entries(node ?? {})) {
    if (key.startsWith("$")) continue;
    collectTokens(value, [...path, key], type, output);
  }
  return output;
}

const sections = sources.map(([label, file]) => {
  const json = JSON.parse(readFileSync(resolve(root, file), "utf8"));
  return [label, collectTokens(json)];
});

const lines = [
  "/* This file is generated by scripts/build-tokens.mjs. Do not edit directly. */",
  ":root {",
];
for (const [index, [label, tokens]] of sections.entries()) {
  lines.push(...(index ? ["", `  /* ${label} tokens */`] : [`  /* ${label} tokens */`]));
  for (const token of tokens) {
    const name = token.path.map(kebab).join("-");
    lines.push(`  --aa-${name}: ${token.value};`);
  }
}
lines.push("}", "");
const next = lines.join("\n");

if (checkOnly) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== next) {
    console.error("Generated token CSS is stale. Run `pnpm tokens:build`.");
    process.exit(1);
  }
  console.log("Generated token CSS is current.");
} else {
  writeFileSync(outputPath, next);
  console.log(`Wrote ${outputPath}`);
}
